/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;


public class kasir extends javax.swing.JFrame {

    /**
     * Creates new form kasir
     */
    Connection con;
    Statement stat;
    ResultSet rs;
    Object row = new Object[5];
    PreparedStatement pst;
    
    
    
    public kasir() {
        initComponents();
        koneksi koneksi = new koneksi();
        koneksi.config();
        con = koneksi.con;
        stat = koneksi.stm;
        setDate();
  
     
        txt_pembayaran.setText("");
        txt_jumlah_harga.setText("0");
        txt_kembalian.setText("0");
        

        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
        private void setDate(){
        LocalDateTime ld = LocalDateTime.now();
        
        DateTimeFormatter ldfor = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        String formattedDate = ld.format(ldfor);
        txt_tgl_Pesanan.setText(formattedDate);
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        no_nota = new javax.swing.JLabel();
        txt_no_nota = new javax.swing.JTextField();
        tgl_pesanan = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_tgl_Pesanan = new javax.swing.JTextField();
        txt_nama_pelangan = new javax.swing.JTextField();
        ComboBox_Pesanan = new javax.swing.JComboBox<>();
        x = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        txt_harga = new javax.swing.JTextField();
        txt_jumlahPesanan = new javax.swing.JTextField();
        Order = new javax.swing.JButton();
        txt_jumlah_harga = new javax.swing.JTextField();
        txt_pembayaran = new javax.swing.JTextField();
        txt_kembalian = new javax.swing.JTextField();
        pembayaran = new javax.swing.JLabel();
        kembalian = new javax.swing.JLabel();
        jumlah_harga = new javax.swing.JLabel();
        jumlah_pesanan = new javax.swing.JLabel();
        Harga = new javax.swing.JLabel();
        cetak_nota = new javax.swing.JButton();
        pesanan = new javax.swing.JLabel();
        Bayar = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();

        jButton8.setText("jButton8");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Kasir Mie Ayam & Bakso Wonogiri");

        no_nota.setText("no nota");

        txt_no_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_no_notaActionPerformed(evt);
            }
        });

        tgl_pesanan.setText("tgl_pesanan");

        jLabel3.setText("nama pelangan");

        txt_tgl_Pesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tgl_PesananActionPerformed(evt);
            }
        });

        txt_nama_pelangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_pelanganActionPerformed(evt);
            }
        });

        ComboBox_Pesanan.setBackground(new java.awt.Color(204, 255, 204));
        ComboBox_Pesanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mie Ayam", "Bakso", "Mie Ayam + Bakso", "Mie Ayam + es teh", "Bakso + es teh", "Mie Ayam + es jeruk", "Bakso + es jeruk", "Mie Ayam + Air Mineral Botol", "Bakso + Air Mineral", "Mie Ayam + teh hangat", "Bakso + teh hangat", "Mie Ayam + jeruk hangat", "Bakso + jeruk hangat", "Mie Ayam + Bakso + 2 es teh", "Mie Ayam + Bakso + 2 es jeruk", "Mie Ayam + Bakso + 2 teh hangat", "Mie Ayam + Bakso + 2 jeruk hangat", "Mie Ayam + Bakso + 2 Air Mineral", "Mie Ayam + Bakso + es jeruk + es teh", "Mie Ayam + Bakso + es jeruk + Air Mineral", "Mie Ayam + Bakso + es teh + Air Mineral", " " }));
        ComboBox_Pesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_PesananActionPerformed(evt);
            }
        });

        x.setBackground(new java.awt.Color(255, 51, 51));
        x.setText("x");
        x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xActionPerformed(evt);
            }
        });

        Hapus.setBackground(new java.awt.Color(255, 255, 255));
        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });

        txt_jumlahPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahPesananActionPerformed(evt);
            }
        });

        Order.setBackground(new java.awt.Color(255, 255, 255));
        Order.setText("Order");
        Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderActionPerformed(evt);
            }
        });

        txt_jumlah_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlah_hargaActionPerformed(evt);
            }
        });

        txt_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pembayaranActionPerformed(evt);
            }
        });

        pembayaran.setText("pembayaran");

        kembalian.setText("kembalian");

        jumlah_harga.setText("jumlah harga");

        jumlah_pesanan.setText("jumlah pesanan");

        Harga.setText("Harga");

        cetak_nota.setBackground(new java.awt.Color(255, 255, 255));
        cetak_nota.setText("Cetak Nota");
        cetak_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetak_notaActionPerformed(evt);
            }
        });

        pesanan.setText("pesanan");

        Bayar.setBackground(new java.awt.Color(255, 255, 255));
        Bayar.setText("Bayar");
        Bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarActionPerformed(evt);
            }
        });

        simpan.setBackground(new java.awt.Color(255, 255, 255));
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jumlah_harga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_jumlah_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(kembalian)
                                .addGap(46, 46, 46)
                                .addComponent(txt_kembalian))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pembayaran)
                                .addGap(33, 33, 33)
                                .addComponent(txt_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Hapus)
                        .addGap(26, 26, 26)
                        .addComponent(Cancel)
                        .addGap(31, 31, 31)
                        .addComponent(simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cetak_nota)
                        .addGap(24, 24, 24))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(Bayar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(x))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(pesanan))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nama_pelangan, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ComboBox_Pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(no_nota)
                                            .addComponent(tgl_pesanan))
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_tgl_Pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_no_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Harga)
                                            .addComponent(jumlah_pesanan))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_jumlahPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(Order)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(x))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(no_nota)
                    .addComponent(txt_no_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgl_pesanan)
                    .addComponent(txt_tgl_Pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nama_pelangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_Pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesanan))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Harga)
                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_jumlahPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlah_pesanan))
                .addGap(26, 26, 26)
                .addComponent(Order)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlah_harga)
                    .addComponent(txt_jumlah_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pembayaran)
                    .addComponent(txt_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bayar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kembalian)
                    .addComponent(txt_kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cetak_nota)
                    .addComponent(simpan)
                    .addComponent(Hapus)
                    .addComponent(Cancel))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cetak_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetak_notaActionPerformed
        JOptionPane.showMessageDialog(null, "\n              NOTA PEMBAYARAN "
                                            +"\n  MIE AYAM & BAKSO WONOGIRI "
                                            +"\n"+"\n"
                                            +"=========================="
                                            +"\n"+"\n"
                                            +"\nNo Nota                   = "+txt_no_nota.getText()
                                            +"\nTanggal Pesanan = "+txt_tgl_Pesanan.getText()
                                            +"\n"
                                            +"\nNama Pelanggan   = "+txt_nama_pelangan.getText()
                                            +"\nMenu Pesanan       = "+ComboBox_Pesanan.getSelectedItem()
                                            +"\nHarga                        = Rp."+txt_harga.getText()
                                            +"\nJumlah Pesanan    = Rp."+txt_jumlahPesanan.getText()
                                            +"\n"
                                            +"\nJumlah Total Harga = Rp."+txt_jumlah_harga.getText()
                                            +"\nPembayaran              = Rp."+txt_pembayaran.getText()
                                            +"\nKembalian                  = Rp."+txt_kembalian.getText()
                                            +"\n\n           SELAMAT MENIKMATI :)","Nota",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_cetak_notaActionPerformed

    private void txt_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pembayaranActionPerformed
 
    }//GEN-LAST:event_txt_pembayaranActionPerformed

    private void txt_jumlah_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlah_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jumlah_hargaActionPerformed

    private void OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderActionPerformed
        int Harga = Integer.parseInt(txt_harga.getText());
        int jumlah_pesanan = Integer.parseInt(txt_jumlahPesanan.getText());
        int jumlah_harga = (Harga*jumlah_pesanan);
        txt_jumlah_harga.setText(Integer.toString(jumlah_harga));
    }//GEN-LAST:event_OrderActionPerformed

    private void txt_jumlahPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahPesananActionPerformed

    }//GEN-LAST:event_txt_jumlahPesananActionPerformed

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_xActionPerformed

    private void ComboBox_PesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_PesananActionPerformed
        String pesanan = (String)ComboBox_Pesanan.getSelectedItem();
        String sql = "select * from tb_menu where menu='"+pesanan+"'";
        try{
            rs = stat.executeQuery(sql);
            while (rs.next()) {
                String nama = rs.getString("menu");
                txt_harga.setText(rs.getString("harga"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
                               
    }//GEN-LAST:event_ComboBox_PesananActionPerformed

    private void txt_nama_pelanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama_pelanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_pelanganActionPerformed

    private void txt_tgl_PesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tgl_PesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tgl_PesananActionPerformed

    private void txt_no_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_no_notaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_no_notaActionPerformed

    private void BayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarActionPerformed
        int jumlah_harga = Integer.parseInt(txt_jumlah_harga.getText());
        int pembayaran = Integer.parseInt(txt_pembayaran.getText());
        int kembalian = (pembayaran-jumlah_harga)*+1;
        txt_kembalian.setText(Integer.toString(kembalian));
    }//GEN-LAST:event_BayarActionPerformed
 private void hapusAll(){
     txt_no_nota.setText("");
        txt_nama_pelangan.setText("");
        ComboBox_Pesanan.setSelectedIndex(0);
        txt_harga.setText("0");
        txt_jumlahPesanan.setText("0");
        txt_jumlah_harga.setText("0");
        txt_pembayaran.setText("");
        txt_kembalian.setText("0");
 }
    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        hapusAll();
    }//GEN-LAST:event_HapusActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
           try{
            koneksi koneksi = new koneksi();
            Statement st = con.createStatement();
            
            String sql = "insert into tb_penjualan values('"+txt_no_nota.getText()+"','"+txt_tgl_Pesanan.getText()
                    +"','"+txt_nama_pelangan.getText()+"','"+ComboBox_Pesanan.getSelectedItem()+"','"+txt_harga.getText()+"','"+txt_jumlahPesanan.getText()+"','"+txt_jumlah_harga.getText()+"')";
            int row = st.executeUpdate(sql);
            
            if (row==1){
                JOptionPane.showMessageDialog(null, "Data sudah di Simpan ","informasi",JOptionPane.INFORMATION_MESSAGE);
                con.close();
            }
            }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data tidak di Simpan","informasi",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
      try{
            koneksi ObjKoneksi = new koneksi();
            Statement st = con.createStatement();
            
            String sql = "delete from tb_penjualan where no_nota = '"+txt_no_nota.getText()+"' ";
            
            int row = st.executeUpdate(sql);
            if(row==1){
                JOptionPane.showMessageDialog(null,"Data sudah dihapus dari " + "database","informasi",JOptionPane.INFORMATION_MESSAGE);
                con.close();
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data tidak dihapus","informasi",JOptionPane.INFORMATION_MESSAGE);
        }
      
    }//GEN-LAST:event_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bayar;
    private javax.swing.JButton Cancel;
    private javax.swing.JComboBox<String> ComboBox_Pesanan;
    private javax.swing.JButton Hapus;
    private javax.swing.JLabel Harga;
    private javax.swing.JButton Order;
    private javax.swing.JButton cetak_nota;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jumlah_harga;
    private javax.swing.JLabel jumlah_pesanan;
    private javax.swing.JLabel kembalian;
    private javax.swing.JLabel no_nota;
    private javax.swing.JLabel pembayaran;
    private javax.swing.JLabel pesanan;
    private javax.swing.JButton simpan;
    private javax.swing.JLabel tgl_pesanan;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_jumlahPesanan;
    private javax.swing.JTextField txt_jumlah_harga;
    private javax.swing.JTextField txt_kembalian;
    private javax.swing.JTextField txt_nama_pelangan;
    private javax.swing.JTextField txt_no_nota;
    private javax.swing.JTextField txt_pembayaran;
    private javax.swing.JTextField txt_tgl_Pesanan;
    private javax.swing.JButton x;
    // End of variables declaration//GEN-END:variables


}
    

